name: Deploy to beatriceundfabian.de - Spinup WP

on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: beatriceundfabian.de
      url: https://beatriceundfabian.de
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: none
          tools: composer:v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "npm"

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install Composer Dependencies for Theme
        run: composer install --no-dev --optimize-autoloader --working-dir=themes/firefly-theme

      - name: Install Composer Dependencies for Plugin
        run: composer install --no-dev --optimize-autoloader --working-dir=mu-plugins/firefly-plugin

      - name: Install NPM Dependencies
        run: npm install

      - name: Build Files
        run: npm run build

      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v5.1.1
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOYMENT_PRIVATE_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOYMENT_SERVER_IP }}
          REMOTE_USER: ${{ secrets.DEPLOYMENT_SSH_USERNAME }}
          TARGET: ${{ vars.DEPLOYMENT_TARGET_FOLDER }}
          EXCLUDE: /node_modules/, /.git/
          SCRIPT_BEFORE: |
            echo "Home: $HOME"
            echo "User: $(whoami)"
            ls -la ~/
            ls -la ~/sites/ || true
            ls -la ~/sites/beatriceundfabian.de/ || true
            ls -la ~/sites/beatriceundfabian.de/files/ || true
          SCRIPT_BEFORE_REQUIRED: "true"
